obj-m += matteo_tc.o
obj-m += q_htb.o
obj-m += f_fw.o

matteo_tc-y := tc.o \
		tc_qdisc.o  \
		tc_class.o  \
		tc_filter.o  \
		../lib/libnetlink.o \
		../lib/ll_proto.o \
		../lib/utils.o \
		tc_util.o \
		tc_stab.o \
		tc_core.o \
		m_police.o 
